### ISSUE TITLE
Enhancement - Using infix `on` instead of operator unaryPlus

### ISSUE THREAD

**Issue by msasikanth** [arunkumar9t2/transition-x#1]
Right now the library allows to set the target using `+` operator
`constraintLayout.transition {
      +helloWorldText 
} `

instead of using that, using a infix function named as on will make more sense

eg: `constraintLayout.transition {
     on helloWorldText
}`

**Comment by arunkumar9t2** [comment]
Hey,

That's a nice idea. But currently Kotlin does not support using `infix` function in a lamda receiver context. This means instead of writing `on helloWorldText` it would be `this on helloWorldText`  or `on(helloWorldText)` which kinda breaks the point of simpler syntax. 

For now I am keeping the `+` for add target `-` for remove target.

More about infix inside lamda : https://youtrack.jetbrains.com/issue/KT-1292
